### ISSUE TITLE
Contribution pages with memberships timing out with logged in users

### ISSUE THREAD

**Issue by herbdool** [civicrm/org.civicrm.module.cividiscount#124]
Something caused a regression with the 3.x of this extension, as far as I can tell. Just upgraded to 4.6.8 and 3.x of this extension.

Have been using this extension in Civi 4.4.x with v 2.6. on contribution forms with memberships. The client had created hundreds of discounts (single use discounts) but loaded fine on the page.

Now after the upgrade _all_ contribution pages with memberships (even memberships with no assigned discount) time out. Error logs can only tell me that it has exceeded the maximum execution time and New Relic is showing heavy database calls from Civi.

There are two conditions where I can get the page to load:
1. Make most discounts inactive so there are only a couple hundred tops. Page still loads quite _slowly_ but it loads (14 seconds in 4.6.8/3.x compared to 3 seconds in 4.4.19/2.6)
2. Or, view the contrib pages as anonymous (3 seconds in 4.6.8/3.x).

This suggests that it keeps trying to check if the current user is eligible for any discounts, or something like that.

I'm going to ask the client if they need all those discount codes active _but_ seems like worth reporting that there is an upper bound to how many discounts can be checked _before_ a page is fully loaded. Funnily, they never had this problem with the older 2.x versions.

**Comment by veda-consulting** [comment]
@herbdool I think the issue your facing is the one thats being addressed in this PR https://github.com/dlobo/org.civicrm.module.cividiscount/pull/115

I think we should probably be able to get it resolved within a few days and back, so allowing a week or so before a new version is released.

**Comment by herbdool** [comment]
So looks like #115 isn't resolved so this issue is still outstanding.

**Comment by konadave** [comment]
`DiscountCalculator __construct($entity, $entity_id, $contact_id, $code, $is_display_field_mode)`

A discount calculator is created in cividiscount_civicrm_buildAmount()

`$dicountCalculater = new CRM_CiviDiscount_DiscountCalculator($pagetype, $eid, $contact_id, $code, FALSE);`

For a membership contribution page, the values that are passed to the constructor are 'membership', NULL (because contribution page doesn't have an eventID), the contact ID, a discount code if it was entered, and FALSE. The subsequent call to `$discountCalculator->getDiscounts()` eventually leads to `checkDiscountsByEntity()` for each discount code, and this is where things go south.

    protected function checkDiscountsByEntity($discount, $entity, $id, $type, $additionalFilter = array()) {
    try {
      if (!isset($discount[$type][$entity])) {
        return FALSE;
      }
      if (empty($discount[$type][$entity])) {
        return TRUE;
      }

      $params = $discount[$type][$entity] + array_merge(array(
          'options' => array('limit' => 999999999),
          'return' => 'id',
        ), $additionalFilter);
      $ids = civicrm_api3($entity, 'get', $params);
      if ($id) {
        return in_array($id, array_keys($ids['values']));
      }
      else {
        return !empty($ids['values']);
      }
    }
    catch (Exception $e) {
      return FALSE;
    }
  }

If the `$discount` is for a membership, `$entity` is set to "membership", `$id` is NULL, and `$type` is 'filters'. `$params` ends up looking something like...

    $params = array(
    'membership_type_id' => array(
      'IN' => array(1, 5),
    ),
    options => array(
      'limit' => '999999999',
    ),
    'return' => 'id'
  );

  Then the get API is called on membership, returning every membership ID of the specified types. In the case of the client I'm working with, that's over 140K. It's taking 4-5 seconds, and this happens for every membership discount code. Then if an `$id` was passed in, it checks to see if it was one of the returned values, and if no `$id` is passed just having any existing membership of the specified types is enough. This seems like the most inefficient way of doing that.

    $params = $discount[$type][$entity];
    if ($id) {
      $params['id'] = $id;
    }
    $result = civicrm_api3($entity, 'get', $params);
    return $result['count'] > 0;

Wouldn't that produce the exact same result, I know it speeds it up. I don't know if this breaks something else.

**Comment by eileenmcnaughton** [comment]
This can be closed now
